### ISSUE TITLE
Bug with cache

### ISSUE THREAD

**Issue by plyq** [alphamatic/amp#1047]
If you run this:
```python
#!/usr/bin/env python
import helpers.cache as hcac

class Gun:
    def __init__(self, model: str):
        self._model = model

    @hcac.cache
    def pew(self, n: int) -> str:
        string = ""
        for _ in range(n):
            string += "pe" + ("w" * len(self._model)) + " "
        return string


if __name__ == "__main__":
    gun = Gun("Makarov")
    print(gun.pew(10))
```
you will get this:
```bash
> python cachetest.py 
Traceback (most recent call last):
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/joblib/func_inspect.py", line 265, in filter_args
    arg_dict[arg_name] = arg_defaults[position]
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cachetest.py", line 18, in <module>
    print(gun.pew(10))
  File "/commodity_research/amp/helpers/cache.py", line 245, in __call__
    obj = self._execute_func(*args, **kwargs)
  File "/commodity_research/amp/helpers/cache.py", line 533, in _execute_func
    obj = self._execute_func_from_mem_cache(*args, **kwargs)
  File "/commodity_research/amp/helpers/cache.py", line 491, in _execute_func_from_mem_cache
    func_id, args_id = self._get_identifiers("mem", args, kwargs)
  File "/commodity_research/amp/helpers/cache.py", line 398, in _get_identifiers
    func_id, args_id = cache_backend._get_output_identifiers(*args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/joblib/memory.py", line 620, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/joblib/memory.py", line 614, in _get_argument_hash
    return hashing.hash(filter_args(self.func, self.ignore, args, kwargs),
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/joblib/func_inspect.py", line 273, in filter_args
    ) from e
ValueError: Wrong number of arguments for pew(self, n: int) -> str:
     pew(10, ) was called.
```

Looks like bug. Need to fix.

**Comment by gpsaggese** [comment]
All done here
