### ISSUE TITLE
Break in GH actions: 2021-06-10

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1468]
`amp` is broken with

```
Run invoke docker_pull --images="current"
INFO: > cmd='/home/runner/.local/bin/invoke docker_pull --images=current'
WARNING: The env var CONTAINER_VERSION should be defined when running inside a container
  -> is_inside_container=True: code_version=amp-1.1.1, container_version=None, is_inside_docker=False, is_inside_ci=True, CI_defined=True, CI='true'
Traceback (most recent call last):
  File "/home/runner/.local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/home/runner/.local/lib/python3.8/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/home/runner/.local/lib/python3.8/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/home/runner/.local/lib/python3.8/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/runner/.local/lib/python3.8/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/amp/amp/tasks.py", line 68, in <module>
    ECR_BASE_PATH = os.environ["AM_ECR_BASE_PATH"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AM_ECR_BASE_PATH'
```

It seems that for some reason the

**Comment by gpsaggese** [comment]
It seems that GH was caching the Docker image locally for lemonade but not for amp, thus the bug was manifesting only in one part. The root cause of the issue is that we didn't propagate the env var everywhere.

Let me fix this issue everywhere.

**Comment by gpsaggese** [comment]
Fixed
