### ISSUE TITLE
S3 denying access intermittently

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1473]
I've changed the way the S3 permissions are handled, but in a way that should be equivalent to the old one, but I am getting intermittent failures like 

```
===================================================================================================== FAILURES =====================================================================================================
_________________________________________________________________________________ TestKibotMetadata.test_get_expiry_contract_slow1 _________________________________________________________________________________
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "/venv/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 1003, in _info
    out = await self._simple_info(path)
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 916, in _simple_info
    out = await self._call_s3(
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "/venv/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/amp/im/kibot/metadata/test/test_kibot_metadata.py", line 89, in test_get_expiry_contract_slow1
    cls = kmd.KibotMetadata()
  File "/app/amp/im/kibot/metadata/load/kibot_metadata.py", line 74, in __init__
    self.minutely_metadata = self._compute_kibot_metadata("1min")
  File "/app/amp/im/kibot/metadata/load/kibot_metadata.py", line 161, in _compute_kibot_metadata
    one_min_contract_metadata = cls.read_1min_contract_metadata()
  File "/app/amp/im/kibot/metadata/load/s3_backend.py", line 51, in read_1min_contract_metadata
    df = pd.read_csv(file_name, index_col=0, nrows=self._max_rows)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/venv/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/venv/lib/python3.8/site-packages/pandas/io/common.py", line 344, in _get_filepath_or_buffer
    file_obj = fsspec.open(
  File "/venv/lib/python3.8/site-packages/fsspec/core.py", line 134, in open
    out = self.__enter__()
  File "/venv/lib/python3.8/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/venv/lib/python3.8/site-packages/fsspec/spec.py", line 942, in open
    f = self._open(
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 498, in _open
    return S3File(
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 1738, in __init__
    super().__init__(
  File "/venv/lib/python3.8/site-packages/fsspec/spec.py", line 1270, in __init__
    self.details = fs.info(path)
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 1007, in _info
    out = await self._version_aware_info(path, version_id)
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 950, in _version_aware_info
    out = await self._call_s3(
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
```

The tricky problem is that it happens only during the regression and not when I run the test by itself.

It seems to be due to interactions between tests but I don't see how it's possible.

**Comment by gpsaggese** [comment]
My gut feeling (based on some circumstantial evidence) is that the new approach to select the S3 credentials is not robust.
1) we can't rely on fixed default credentials, since we might have different S3 profiles
2) if I use `default` profile in `.aws` things work, if I use `am` profile it gets rickety
3) not all the code goes through boto, sometimes (for tests that fail!) we go through pandas bindings for S3
4) we had a related problem when running on GH Actions since GH doesn't have `.aws` credentials so we had to use environment vars

**Comment by gpsaggese** [comment]
All done here
