### ISSUE TITLE
Break in GH Actions: 2021-06-15

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1477]
Fast tests
```
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_dtypes1
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_read_data1
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_read_data2
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_read_data3
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_read_data_check_date_type
FAILED im/ib/data/load/test/test_s3_data_loader.py::TestS3IbDataLoader1::test_read_data_with_start_end_ts
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_parse_symbols_file1
FAILED helpers/test/test_s3.py::Test_s3_get_credentials1::test2 - AssertionEr...
```

Slow tests
```
FAILED im/kibot/data/load/test/test_s3_data_loader.py::TestKibotS3DataLoader::test1
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_expiry_contract_slow1
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_futures_slow1
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_futures_slow2
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_metadata_slow1
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_metadata_slow2
FAILED im/kibot/metadata/test/test_kibot_metadata.py::TestKibotMetadata::test_get_metadata_slow3
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_1
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_2
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_3
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_4
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_parse_symbols_file2
FAILED core/test/test_dataflow_source_nodes.py::TestKibotEquityReader::test1
```

I will disable the tests for now

**Comment by gpsaggese** [comment]
Related to this also in `lem`

```
FAILED dataflow_lemonade/futures_returns/test/test_futures_returns_pipeline.py::TestReturnsBuilder::test1
FAILED dataflow_lemonade/RH3F/test/test_RH3F_pipeline1.py::TestPcaModelBuilder::test1
FAILED dataflow_lemonade/RH3F/test/test_source_nodes.py::TestContinuousContractBuilder::test1
FAILED dataflow_lemonade/RH2F/test/test_RH2F_pipeline.py::TestArModelBuilder::test1
FAILED dataflow_lemonade/RH1F/test/test_RH1F_pipeline.py::TestArModelBuilder1::test1
FAILED dataflow_lemonade/RH1F/test/test_task11_pipeline.py::TestArModelBuilder2::test1
```

due to 

```
___________________________ TestReturnsBuilder.test1 ___________________________
Traceback (most recent call last):
  File "/app/amp/core/dataflow/core.py", line 407, in _run_node
    output = getattr(node, method)(**kwargs)
  File "/app/amp/core/dataflow_source_nodes.py", line 85, in fit
    self._lazy_load()
  File "/app/amp/core/dataflow_source_nodes.py", line 95, in _lazy_load
    self.df = vkibot.KibotS3DataLoader().read_data(
  File "/app/amp/im/kibot/data/load/kibot_s3_data_loader.py", line 34, in read_data
    return self._read_data(
  File "/app/amp/im/kibot/data/load/kibot_s3_data_loader.py", line 72, in _read_data
    data = self._read_csv(file_path, frequency, start_ts, end_ts, nrows)
  File "/app/amp/helpers/cache.py", line 249, in __call__
    obj = self._execute_func(*args, **kwargs)
  File "/app/amp/helpers/cache.py", line 537, in _execute_func
    obj = self._execute_func_from_mem_cache(*args, **kwargs)
  File "/app/amp/helpers/cache.py", line 516, in _execute_func_from_mem_cache
    obj = self._execute_func_from_disk_cache(*args, **kwargs)
  File "/app/amp/helpers/cache.py", line 491, in _execute_func_from_disk_cache
    obj = self._disk_cached_func(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/venv/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/app/amp/im/kibot/data/load/kibot_s3_data_loader.py", line 89, in _read_csv
    data = pdhelp.read_csv(
  File "/app/amp/core/pandas_helpers.py", line 287, in read_csv
    df = pd.read_csv(file_name, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 717, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/dataflow_lemonade/futures_returns/test/test_futures_returns_pipeline.py", line 20, in test1
    result_bundle = dag_runner.fit()
  File "/app/amp/core/dataflow/runners.py", line 78, in fit
    return self._run_dag(self._result_nid, "fit")
  File "/app/amp/core/dataflow/runners.py", line 94, in _run_dag
    df_out = self.dag.run_leq_node(nid, method)["df_out"]
  File "/app/amp/core/dataflow/core.py", line 387, in run_leq_node
    self._run_node(n, method)
  File "/app/amp/core/dataflow/core.py", line 409, in _run_node
    raise Exception(f"An exception occurred in node '{nid}'.") from e
Exception: An exception occurred in node 'rets/read_data'.
```

**Comment by gpsaggese** [comment]
Started some work in `AmpTask1477_Break_in_GH_Actions_2021_06_15`

**Comment by gpsaggese** [comment]
Fixed
