### ISSUE TITLE
Break 2021-07-18

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1549]
https://github.com/alphamatic/amp/runs/3099185310?check_suite_focus=true

Failures are due to the 
```
################################################################################
* Failed assertion *
File '/root/.aws/credentials' doesn't exist
################################################################################
```

This is a bit of a tricky issue:
- GitHub actions doesn't have a `~/.aws/credentials` but gets the vars through env vars
- The env vars need to be passed through Docker, so they are always defined, even if empty
- We need different env vars for different S3 buckets

A solution is:
- always define the env vars
- if they are all empty use `~/.aws/credentials`
- if they are not empty they override `~/.aws/credentials`

**Comment by gpsaggese** [comment]
The first failure is:

```
=================================== FAILURES ===================================
____________ TestIbFilePathGenerator.test_get_latest_symbols_file1 _____________
Traceback (most recent call last):
  File "/app/amp/im/ib/data/load/test/test_file_path_generator.py", line 32, in test_get_latest_symbols_file1
    latest_file = ifpgen.IbFilePathGenerator.get_latest_symbols_file()
  File "/app/amp/im/ib/data/load/ib_file_path_generator.py", line 82, in get_latest_symbols_file
    files = hs3.ls(file_prefix)
  File "/app/amp/helpers/s3.py", line 384, in ls
    s3 = _get_boto3_resource(aws_profile=aws_profile)
  File "/app/amp/helpers/s3.py", line 184, in _get_boto3_resource
    aws_credentials = get_aws_credentials(*args, **kwargs)
  File "/app/amp/helpers/s3.py", line 95, in get_aws_credentials
    config = _get_aws_config(file_name)
  File "/app/amp/helpers/s3.py", line 38, in _get_aws_config
    dbg.dassert_file_exists(file_name)
  File "/app/amp/helpers/dbg.py", line 514, in dassert_file_exists
    _dfatal(txt, msg, *args)
  File "/app/amp/helpers/dbg.py", line 115, in _dfatal
    dfatal(dfatal_txt)
  File "/app/amp/helpers/dbg.py", line 61, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
File '/root/.aws/credentials' doesn't exist
################################################################################
```

The problem is that there is legacy code that doesn't rely on s3fs but goes straight to boto, so the improved authentication is not exercised.

It shows only in GH. Let me try to repro in my client.

**Comment by gpsaggese** [comment]
```
pytest -x amp/im/ib/data/load/test/test_file_path_generator.py::TestIbFilePathGenerator::test_get_latest_symbols_file1
```

For some reason `lem` has the `AWS_` env vars set up, while `amp` not.

In any case I see that in both cases even if `AWS_` env vars are set up the code looks for the aws authentication file.

In general this difference between GH action and user setup is a pain in the neck. Maybe we need a more general solution

**Comment by gpsaggese** [comment]
Our boto `ls` implementation should be easy to remove

```
> jackpy "hs3.ls"
im/ib/data/load/ib_file_path_generator.py:82:        files = hs3.ls(file_prefix)
im/ib/data/extract/ib_data_extractor.py:220:            hs3.ls("%s/" % part_files_dir)
helpers/test/test_s3.py:42:        file_names = hs3.ls(file_path)
```

```
> jackpy "hs3.exists"
im/kibot/data/extract/download.py:217:            exists = hs3.exists(aws_file)
im/common/metadata/symbols.py:162:                if not hs3.exists(path):
im/ib/data/load/ib_s3_data_loader.py:118:                hs3.exists(file_path), True, msg=f"S3 key not found: {file_path}"
im/ib/data/load/ib_file_path_generator.py:90:        dbg.dassert(hs3.exists(latest_file))
im/ib/data/extract/gateway/utils.py:457:        hs3.exists(file_name)
```

```
> jackpy "hs3.listdir"
im/kibot/notebooks/kibot_volume_statistics.py:125:    payloads = hs3.listdir(dataset_aws_directory, mode="non-recursive")
im/kibot/metadata/load/s3_backend.py:228:            for filename in hs3.listdir(aws_csv_gz_dir)
helpers/test/test_s3.py:48:        file_names = hs3.listdir(file_path, mode="non-recursive")
helpers/csv_helpers.py:253:        filenames = hs3.listdir(csv_dir)
```

```
> jackpy "hs3.parse_path"
helpers/test/test_s3.py:30:        bucket_name, file_path = hs3.parse_path(file_path)
```

**Comment by gpsaggese** [comment]
After a first re-write to use s3fs the remaining failures are:

```
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_1 - AssertionError:
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_2 - AssertionError:
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_3 - AssertionError:
FAILED im/ib/metadata/test/test_ib_symbols.py::TestIbSymbolUniverse::test_get_4 - AssertionError:
FAILED im/ib/data/load/test/test_file_path_generator.py::TestIbFilePathGenerator::test_get_latest_symbols_file1 - AssertionError:
```

**Comment by gpsaggese** [comment]
Everything green
