### ISSUE TITLE
Break - 2021-08-03

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1610]
```
=================================== FAILURES ===================================
____________________ TestRunExperimentSuccess1.test_serial1 ____________________
Traceback (most recent call last):
  File "/app/core/dataflow_model/test/test_run_experiment.py", line 53, in test_serial1
    _run_experiment_helper(self, cmd_opts, exp_pass, self.EXPECTED_OUTCOME)
  File "/app/core/dataflow_model/test/test_run_experiment.py", line 267, in _run_experiment_helper
    trnot.run_cmd_line(self, cmd, cmd_opts, dst_dir, exp, exp_pass)
  File "/app/dev_scripts/test/test_run_notebook.py", line 278, in run_cmd_line
    rc = si.system(cmd, abort_on_error=abort_on_error, suppress_output=False)
  File "/app/helpers/system_interaction.py", line 291, in system
    rc, _ = _system(
  File "/app/helpers/system_interaction.py", line 264, in _system
    raise RuntimeError(
RuntimeError: cmd='(/app/core/dataflow_model/run_experiment.py --experiment_builder core.dataflow_model.test.simple_experiment.run_experiment --dst_dir /app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch --config_builder 'dev_scripts.test.test_run_notebook.build_configs1()' --num_threads 'serial') 2>&1' failed with rc='1'
truncated output=
INFO: > cmd='/app/core/dataflow_model/run_experiment.py --experiment_builder core.dataflow_model.test.simple_experiment.run_experiment --dst_dir /app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch --config_builder dev_scripts.test.test_run_notebook.build_configs1() --num_threads serial'
INFO: Saving log to file '/app/core/dataflow_model/run_experiment.py.log'
08-03_20:38 INFO  builder             : get_configs_from_builder      : 34  : Executing function 'dev_scripts.test.test_run_notebook.build_configs1()'
08-03_20:38 INFO  utils               : get_configs_from_command_line : 197 : Generated 2 configs from the builder
08-03_20:38 INFO  utils               : select_config                 : 171 : Selected 2 configs
08-03_20:38 INFO  utils               : get_configs_from_command_line : 202 : Selected 2 configs from command line
08-03_20:38 INFO  utils               : get_configs_from_command_line : 206 : Removed 0 configs since already executed
08-03_20:38 INFO  utils               : get_configs_from_command_line : 207 : Need to execute 2 configs
08-03_20:38 INFO  run_experiment      : _main                         : 167 : log_file='/app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/log.20210803-203832.txt'
08-03_20:38 INFO  joblib_helpers      : parallel_execute              : 313 : dry_run=False, num_threads='serial', incremental=True, num_attempts=1, abort_on_error=True
08-03_20:38 INFO  joblib_helpers      : parallel_execute              : 322 : Saving log info in '/app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/log.20210803-203832.txt'
08-03_20:38 INFO  joblib_helpers      : parallel_execute              : 323 : Number of tasks=2

Running serial tasks:   0%|          | 0/2 [00:00<?, ?it/s]08-03_20:38 INFO  utils               : setup_experiment_dir          : 129 : Creating experiment dir '/app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/result_0'
08-03_20:38 INFO  pickle_             : to_pickle                     : 64  : Saved '/app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/result_0/config.pkl' (size=0.00 Mb, time=0.0s)
08-03_20:38 INFO  run_experiment      : _run_experiment               : 57  : 
################################################################################
Executing experiment for config 0
################################################################################
08-03_20:38 INFO  run_experiment      : _run_experiment               : 58  : config=
fail: False
id: 0
meta:
  id: 0
  config_builder: dev_scripts.test.test_run_notebook.build_configs1()
  dst_dir: /app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch
  experiment_builder: core.dataflow_model.test.simple_experiment.run_experiment
  experiment_result_dir: /app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/result_0
08-03_20:38 INFO  run_experiment      : _run_experiment               : 80  : Executing '/app/core/dataflow_model/run_experiment_stub.py --experiment_builder 'core.dataflow_model.test.simple_experiment.run_experiment' --config_builder 'dev_scripts.test.test_run_notebook.build_configs1()' --config_idx 0 --dst_dir /app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch -v INFO'
08-03_20:38 INFO  run_experiment      : _run_experiment               : 84  : Executed cmd
08-03_20:38 INFO  utils               : mark_config_as_success        : 115 : Creating file_name='/app/core/dataflow_model/test/TestRunExperimentSuccess1.test_serial1/tmp.scratch/result_0/success.txt'
```

**Comment by gpsaggese** [comment]
```
FAILED amp/core/dataflow_model/test/test_run_experiment.py::TestRunExperimentSuccess1::test_parallel1
FAILED amp/core/dataflow_model/test/test_run_experiment.py::TestRunExperimentArchiveOnS3::test_serial1
```

Everything is passing on my side. Unclear what is the difference with GH Actions.

**Comment by gpsaggese** [comment]
The first test is fixed. Debugging the second one. Probably some discrepancy in how GH authenticates AWS

**Comment by gpsaggese** [comment]
That problem is fixed but still GH is not happy

```
08-04_12:47 INFO  system_interaction  : _system                       : 202 : > (tar tvf /app/core/dataflow_model/test/TestRunExperimentArchiveOnS3.test_serial1/tmp.20210804-124708.scratch.tgz) 2>&1
08-04_12:47 INFO  s3                  : archive_data_on_s3            : 410 : Copying '/app/core/dataflow_model/test/TestRunExperimentArchiveOnS3.test_serial1/tmp.20210804-124708.scratch.tgz' to 's3://***/tmp/tmp.20210804-124708.scratch.tgz'

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "/venv/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/core/dataflow_model/run_experiment.py", line 211, in <module>
    _main(_parse())
  File "/app/core/dataflow_model/run_experiment.py", line 201, in _main
    s3_path = hs3.archive_data_on_s3(dst_dir, s3_path, aws_profile)
  File "/app/helpers/s3.py", line 414, in archive_data_on_s3
    s3fs_.put(dst_path, s3_file_path)
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 283, in _put
    return await _throttled_gather(
  File "/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 144, in _throttled_gather
    results.extend(await asyncio.gather(*chunk, **gather_kwargs))
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 853, in _put_file
    return await self._call_s3(
  File "/venv/lib/python3.8/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Access Denied
```

**Comment by gpsaggese** [comment]
My gut feeling is that GH infra doesn't have permissions to write in that bucket.

```
> aws s3 cp --profile infra_am .gitignore s3://alphamatic-data/tmp
upload failed: ./.gitignore to s3://alphamatic-data/tmp An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by gpsaggese** [comment]
Fixed
