### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by gitpaulsmith** [alphamatic/amp#1704]
We have this failure in GH:
```
=================================== FAILURES ===================================
________________________ TestResultBundle.test_pickle1 _________________________
Traceback (most recent call last):
  File "/app/core/dataflow/test/test_result_bundle.py", line 71, in test_pickle1
    self.assert_equal(str(actual), str(expected))
  File "/app/helpers/unit_test.py", line 1169, in assert_equal
    is_equal = _assert_equal(
  File "/app/helpers/unit_test.py", line 900, in _assert_equal
    diff_files(
  File "/app/helpers/unit_test.py", line 624, in diff_files
    raise RuntimeError(msg_as_str)
RuntimeError: 
--------------------------------------------------------------------------------
ACTUAL vs EXPECTED: TestResultBundle.test_pickle1
--------------------------------------------------------------------------------

# Dir structure                                                           (
/app/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch         |  /app/amp/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch
/app/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch/result_ |  /app/amp/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch/res
Diff with:
> vimdiff core/dataflow/test/TestResultBundle.test_pickle1/tmp.actual.txt core/dataflow/test/TestResultBundle.test_pickle1/tmp.expected.txt
or running:
> ./tmp_diff.sh
--------------------------------------------------------------------------------
EXPECTED VARIABLE: TestResultBundle.test_pickle1
--------------------------------------------------------------------------------
exp = r"""# Dir structure
/app/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch
/app/core/dataflow/test/TestResultBundle.test_pickle1/tmp.scratch/result_bundle.v1_0.pkl"""
```
e.g., see https://github.com/alphamatic/amp/runs/3572365094?check_suite_focus=true

**Comment by gpsaggese** [comment]
Took a look. The problem is that we need to purify the output when the test runs in lemonade vs amp. It should be use an easy fix.

**Comment by gpsaggese** [comment]
There is also a break in lemonade

```
FAILED amp/helpers/test/test_lib_tasks.py::TestLibTasks1::test_get_gh_issue_title1
FAILED amp/helpers/test/test_lib_tasks.py::TestLibTasks1::test_get_gh_issue_title3
FAILED test/test_lib_tasks_lem.py::TestLibTasks1::test_get_gh_issue_title1 - ...
```

```
=================================== FAILURES ===================================
____________________ TestLibTasks1.test_get_gh_issue_title1 ____________________
Traceback (most recent call last):
  File "/app/amp/helpers/test/test_lib_tasks.py", line 411, in test_get_gh_issue_title1
    self.assert_equal(act, exp)
  File "/app/amp/helpers/unit_test.py", line 1151, in assert_equal
    dbg.dassert_in(type(actual), (bytes, str), "actual=%s", str(actual))
  File "/app/amp/helpers/dbg.py", line 225, in dassert_in
    _dfatal(txt, msg, *args)
  File "/app/amp/helpers/dbg.py", line 115, in _dfatal
    dfatal(dfatal_txt)
  File "/app/amp/helpers/dbg.py", line 61, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
'<class 'tuple'>' in '(<class 'bytes'>, <class 'str'>)'
actual=('AmpTask1_Bridge_Python_and_R', 'https://github.com/alphamatic/amp/issues/1')
################################################################################
```

**Comment by gpsaggese** [comment]
Fixed
