### ISSUE TITLE
Build breaks: 2021-09-29

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1755]
There is a failure in the CI

https://github.com/alphamatic/lemonade/runs/3739482960?check_suite_focus=true

```
=================================== FAILURES ===================================
__________________ Test_RH1E_ProdModels.test_end_to_end_slow1 __________________
Traceback (most recent call last):
  File "/app/dataflow_lemonade/RH1E/test/test_RH1E_prod_models.py", line 41, in test_end_to_end_slow1
    actual_outcome = rpmf.run_prod_model_flow(
  File "/app/amp/core/dataflow_model/run_prod_model_flow.py", line 49, in run_prod_model_flow
    _run_model(config_builder, experiment_builder, run_model_opts, run_model_dir)
  File "/app/amp/core/dataflow_model/run_prod_model_flow.py", line 148, in _run_model
    hsinte.system(cmd)
  File "/app/amp/helpers/system_interaction.py", line 293, in system
    rc, _ = _system(
  File "/app/amp/helpers/system_interaction.py", line 266, in _system
    raise RuntimeError(
RuntimeError: cmd='(/app/amp/core/dataflow_model/run_experiment.py --experiment_builder amp.core.dataflow_model.master_experiment.run_experiment --config_builder 'dataflow_lemonade.RH1E.RH1E_configs.build_model_configs("kibot_v1-top1.5T", 1)' --dst_dir /app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model --clean_dst_dir --no_confirm --num_threads serial ) 2>&1' failed with rc='1'
truncated output=
INFO: > cmd='/app/amp/core/dataflow_model/run_experiment.py --experiment_builder amp.core.dataflow_model.master_experiment.run_experiment --config_builder dataflow_lemonade.RH1E.RH1E_configs.build_model_configs("kibot_v1-top1.5T", 1) --dst_dir /app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model --clean_dst_dir --no_confirm --num_threads serial'
INFO: Saving log to file '/app/amp/core/dataflow_model/run_experiment.py.log'
09-28_22:08 INFO  builder             : get_configs_from_builder      : 34  : Executing function 'dataflow_lemonade.RH1E.RH1E_configs.build_model_configs("kibot_v1-top1.5T", 1)'
09-28_22:08 INFO  RH1E_configs        : build_model_configs           : 72  : bm_config='kibot_v1-top1.5T'
09-28_22:08 INFO  RH1E_configs        : build_model_configs           : 78  : universe_as_str='kibot_v1-top1', trading_period='5T'
09-28_22:08 WARN  RH1E_configs        : build_model_configs           : 110 : Considering only the first 1 / 2 configs
09-28_22:08 INFO  utils               : get_configs_from_command_line : 197 : Generated 1 configs from the builder
09-28_22:08 INFO  utils               : select_config                 : 171 : Selected 1 configs
09-28_22:08 INFO  utils               : get_configs_from_command_line : 202 : Selected 1 configs from command line
09-28_22:08 INFO  utils               : get_configs_from_command_line : 206 : Removed 0 configs since already executed
09-28_22:08 INFO  utils               : get_configs_from_command_line : 207 : Need to execute 1 configs
09-28_22:08 INFO  run_experiment      : _main                         : 167 : log_file='/app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model/log.20210928-220826.txt'
09-28_22:08 INFO  joblib_helpers      : parallel_execute              : 302 : dry_run=False, num_threads='serial', incremental=True, num_attempts=1, abort_on_error=True
09-28_22:08 INFO  joblib_helpers      : parallel_execute              : 311 : Saving log info in '/app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model/log.20210928-220826.txt'
09-28_22:08 INFO  joblib_helpers      : parallel_execute              : 312 : Number of tasks=1

Running serial tasks:   0%|          | 0/1 [00:00<?, ?it/s]09-28_22:08 INFO  utils               : setup_experiment_dir          : 129 : Creating experiment dir '/app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model/result_0'
09-28_22:08 INFO  run_experiment      : _run_experiment               : 57  : 
################################################################################
Executing experiment for config 0
################################################################################
09-28_22:08 INFO  run_experiment      : _run_experiment               : 58  : config=
DAG:
  rets/read_data:
    source_node_name: disk
    source_node_kwargs:
      file_path: s3://***/data/kibot/pq/sp_500_1min/AAPL.pq
      aws_profile: 
  rets/filter_ath:
    col_mode: replace_all
    transformer_kwargs:
```

**Comment by gpsaggese** [comment]
From https://github.com/alphamatic/lemonade/runs/3797453996?check_suite_focus=true

```
19:10:08 INFO  run_experiment      : _run_experiment               : 84  : Executing '/app/amp/core/dataflow_model/run_experiment_stub.py --experiment_builder 'amp.core.dataflow_model.master_experiment.run_experiment' --config_builder 'dataflow_lemonade.RH1E.RH1E_configs.build_model_configs("kibot_v1-top1.5T", 1)' --config_idx 0 --dst_dir /app/dataflow_lemonade/RH1E/test/Test_RH1E_ProdModels.test_end_to_end_slow1/tmp.scratch/run_model -v INFO'
  ==> 
run_leq_node:   0%|          | 0/9 [00:00<?, ?it/s]
run_leq_node:   0%|          | 0/9 [00:00<?, ?it/s]
  ==> Traceback (most recent call last):
  ==>   File "/app/amp/core/dataflow_model/run_experiment_stub.py", line 108, in <module>
  ==>     _main(_parse())
  ==>   File "/app/amp/core/dataflow_model/run_experiment_stub.py", line 104, in _main
  ==>     exec(python_code)  # pylint: disable=exec-used
  ==>   File "<string>", line 1, in <module>
  ==>   File "/app/amp/core/dataflow_model/master_experiment.py", line 43, in run_experiment
  ==>     fit_result_bundle = dag_runner.fit()
  ==>   File "/app/amp/core/dataflow/runners.py", line 156, in fit
  ==>     return self._run_dag(method)
  ==>   File "/app/amp/core/dataflow/runners.py", line 186, in _run_dag
  ==>     df_out, info = self._run_dag_helper(method)
  ==>   File "/app/amp/core/dataflow/runners.py", line 103, in _run_dag_helper
  ==>     df_out = self.dag.run_leq_node(nid, method)["df_out"]
  ==>   File "/app/amp/core/dataflow/core.py", line 437, in run_leq_node
  ==>     self._run_node(n, method)
  ==>   File "/app/amp/core/dataflow/core.py", line 463, in _run_node
  ==>     output = getattr(node, method)(**kwargs)
  ==>   File "/app/amp/core/dataflow/nodes/sources.py", line 183, in fit
  ==>     self._lazy_load()
  ==>   File "/app/amp/core/dataflow/nodes/sources.py", line 192, in _lazy_load
  ==>     df = load_data_from_disk(
  ==>   File "/app/amp/core/dataflow/nodes/sources.py", line 120, in load_data_from_disk
  ==>     s3fs = hs3.get_s3fs(aws_profile)
  ==>   File "/app/amp/helpers/s3.py", line 391, in get_s3fs
  ==>     aws_credentials = get_aws_credentials(*args, **kwargs)
  ==>   File "/app/amp/helpers/s3.py", line 273, in get_aws_credentials
  ==>     hdbg.dassert_ne(aws_profile, "")
  ==>   File "/app/amp/helpers/dbg.py", line 145, in dassert_ne
  ==>     _dfatal(txt, msg, *args)
  ==>   File "/app/amp/helpers/dbg.py", line 115, in _dfatal
  ==>     dfatal(dfatal_txt)
  ==>   File "/app/amp/helpers/dbg.py", line 61, in dfatal
  ==>     raise assertion_type(ret)
  ==> AssertionError: 
  ==> ################################################################################
  ==> * Failed assertion *
  ==> ''
  ==> !=
  ==> ''
  ==> ################################################################################
  ==> 
19:10:12 INFO  run_experiment      : _run_experiment               : 88  : Executed cmd
19:10:12 ERROR run_experiment      : _run_experiment               : 94  : Execution failed for experiment 0
19:10:12 ERROR joblib_helpers      : _parallel_execute_decorator   : 237 : Execution failed
19:10:12 ERROR joblib_helpers      : _parallel_execute_decorator   : 251 : 
```
