### ISSUE TITLE
Prepare docker container for cvxpy

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1836]
The specs are:
- minimum deps are cxopy, cvxpy, pandas, numpy, ...
- support docker bash / jupyter interface
- no release flow for now

**Comment by gpsaggese** [comment]
Uhm... cvxpy doesn't install on Ubuntu linux. Let's see why

```
  Command ['/venv/bin/pip', 'install', '--no-deps', 'tmp.pypoetry/artifacts/72/a3/3c/c4ec48894a7a1fbc9526f8fd297a4e7134753462a65e63197d80322ccb/cvxpy-1.1.17-cp38-cp38-manylinux_2_24_x86_64.whl'] errored with the following return code 1, and output:
  ERROR: cvxpy-1.1.17-cp38-cp38-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.
```

**Comment by gpsaggese** [comment]
That problem is solved. Now the issue is
```
+ jupyter contrib nbextension install
Traceback (most recent call last):
  File "/venv/bin/jupyter-contrib", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app = cls.instance(**kwargs)
  File "/venv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/jupyter_contrib_core/application.py", line 27, in __init__
    self._refresh_subcommands()
  File "/venv/lib/python3.8/site-packages/jupyter_contrib_core/application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
  File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-resources>=1.4.0; python_version < "3.9"' distribution was not found and is required by jsonschema
```

**Comment by gpsaggese** [comment]
To run:

```
> cd optimizer
> i docker_pull
> i docker_bash
...
```

The script checks that cvxpy and helpers can be run
```
