### ISSUE TITLE
Break 2021-11-18

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1864]
Fast tests are failing with (https://github.com/alphamatic/amp/runs/4257824166?check_suite_focus=true)

``` 
_____________________ TestDryRunTasks2.test_gh_create_pr1 ______________________
Traceback (most recent call last):
  File "/app/helpers/test/test_lib_tasks.py", line 250, in test_gh_create_pr1
    _gh_login()
  File "/app/helpers/test/test_lib_tasks.py", line 101, in _gh_login
    hsysinte.system(cmd)
  File "/app/helpers/system_interaction.py", line 298, in system
    rc, _ = _system(
  File "/app/helpers/system_interaction.py", line 271, in _system
    raise RuntimeError(
RuntimeError: cmd='(echo $GH_ACTION_ACCESS_TOKEN | gh auth login --with-token) 2>&1' failed with rc='1'
truncated output=
open /home/.config/gh/config.yml: permission denied
```

It seems to be related to a permission issue in the container

**Comment by gpsaggese** [comment]
Instrumenting the code 

```
(0.06 s) > ls -l $HOME/.config
  ==> total 16
  ==> drwxr-xr-x 2 root      root 4096 Nov 18 23:25 gh
  ==> drwxr-xr-x 2 root      root 4096 Nov 18 23:25 gspread_pandas
  ==> drwxr-xr-x 2 user_1001  121 4096 Nov 18 23:25 matplotlib
  ==> drwxrwxrwx 1 root      root 4096 Nov 14 14:31 pypoetry
> ls -l $HOME/.config/gh
  ==> total 0
> ls -l $HOME/.config/gh/config.yml
  ==> ls: cannot access '/home/.config/gh/config.yml': No such file or directory
```

I guess something much have changed on gh side

**Comment by gpsaggese** [comment]
In the local container

```
(0.32 s) > ls -l $HOME/.config
  ==> total 8
  ==> drwxr-x--x 4 root root  128 Aug  4 14:07 gh
  ==> drwxr-xr-x 4 root root  128 Jul  6  2020 gspread_pandas
  ==> drwxr-xr-x 2 root root 4096 Nov 18 12:41 matplotlib
  ==> drwxrwxrwx 1 root root 4096 Nov 14 14:31 pypoetry
> ls -l $HOME/.config/gh
  ==> total 8
  ==> -rw------- 1 root root 522 Nov 19 00:04 config.yml
  ==> -rw------- 1 root root 112 Nov 18 22:53 hosts.yml
> ls -l $HOME/.config/gh/config.yml
  ==> -rw------- 1 root root 522 Nov 19 00:04 /home/.config/gh/config.yml
> touch $HOME/.config/gh/config.yml
> ls -l $HOME/.config/gh/config.yml
  ==> -rw------- 1 root root 522 Nov 19 00:04 /home/.config/gh/config.yml
```

**Comment by gpsaggese** [comment]
The problem started this morning

![image](https://user-images.githubusercontent.com/33238329/142516271-e555c74d-3e37-4e3c-80c3-68cca8a3578c.png)

But

https://github.com/alphamatic/amp/commit/31c7b4a4e5b923fabdfbe781351c116c97736a30

doesn't have any change related to this

**Comment by gpsaggese** [comment]
Done
