### ISSUE TITLE
Move Broker inside Portfolio

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1930]
With the PR https://github.com/alphamatic/amp/pull/1931 that should be just a refactoring all tests are passing but 
`FAILED oms/test/test_place_orders.py::TestOptimizeAndUpdate1::test1` fails.

```
Traceback (most recent call last):
  File "/app/amp/oms/test/test_place_orders.py", line 155, in test1
    hasynci.run(self._test_coroutine(event_loop), event_loop=event_loop)
  File "/app/amp/helpers/hasyncio.py", line 118, in run
    ret = event_loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/amp/oms/test/test_place_orders.py", line 274, in _test_coroutine
    self.assert_dfs_close(actual.to_frame(), expected, rtol=1e-2, atol=1e-2)
  File "/app/amp/helpers/unit_test.py", line 1200, in assert_dfs_close
    np.testing.assert_allclose(actual, expected, **kwargs)
  File "/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.01, atol=0.01

Mismatched elements: 4 / 5 (80%)
Max absolute difference: 100664.01
Max relative difference: 1.
 x: array([[      0.],
       [1000000.],
       [1000000.],...
 y: array([[5.072836e+04],
       [9.492716e+05],
       [1.000000e+06],...
```

It's not clear if the unit test is not compatible with the new timing of the code of there is some other problem

**Comment by gpsaggese** [comment]
```

**Comment by gpsaggese** [comment]
Done
