### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by gitpaulsmith** [alphamatic/amp#1944]
```
=================================== FAILURES ===================================
______________________ TestCachingOnS3.test_with_caching1 ______________________
Traceback (most recent call last):
  File "/app/helpers/test/test_cache.py", line 769, in test_with_caching1
    self._execute_and_check_state(f, cf, 3, 4, exp_cf_state="disk")
  File "/app/helpers/test/test_cache.py", line 154, in _execute_and_check_state
    self.assertEqual(f.executed, exp_f_state)  # type: ignore[attr-defined]
  File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != False
```

**Comment by gitpaulsmith** [comment]
Resolved
