### ISSUE TITLE
Run the RT pipeline with MockedBroker/Portfolio

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#1946]

**Comment by gpsaggese** [comment]
```
> pytest ./oms/test/test_place_orders.py::TestMockedPlaceOrders1 -s --dbg 2>&1 | tee log.txt
```

**Comment by gpsaggese** [comment]
After all the changes the code runs but now asserts at

pytest ./dataflow/pipelines/real_time/test/test_dataflow_amp_real_time_pipeline.py::TestRealTimeMvnReturnsWithOms1 -s --dbg

```
Traceback (most recent call last):
  File "/app/amp/dataflow/pipelines/real_time/test/test_dataflow_amp_real_time_pipeline.py", line 566, in test1
    result_bundles = hasynci.run(
  File "/app/amp/helpers/hasyncio.py", line 120, in run
    ret = event_loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/amp/dataflow/system/real_time_runner.py", line 61, in predict
    result_bundles = [
  File "/app/amp/dataflow/system/real_time_runner.py", line 61, in <listcomp>
    result_bundles = [
  File "/app/amp/dataflow/system/real_time_runner.py", line 76, in predict_at_datetime
    async for event, result_bundle in creatime.execute_with_real_time_loop(
  File "/app/amp/core/real_time.py", line 392, in execute_with_real_time_loop
    result = await asyncio.gather(  # type: ignore[var-annotated]
  File "/app/amp/dataflow/system/real_time_runner.py", line 120, in _run_dag
    df_out, info = self._run_dag_helper(method)
  File "/app/amp/dataflow/core/runners.py", line 103, in _run_dag_helper
    df_out = self.dag.run_leq_node(nid, method)["df_out"]
  File "/app/amp/dataflow/core/dag.py", line 348, in run_leq_node
    self._run_node(n, method)
  File "/app/amp/dataflow/core/dag.py", line 396, in _run_node
    output = getattr(node, method)(**kwargs)
  File "/app/amp/dataflow/core/nodes/base.py", line 250, in predict
    df_out, info = self._transform(df_in)
  File "/app/amp/dataflow/core/nodes/transformers.py", line 726, in _transform
    df_out = self._func(df, **self._func_kwargs)
  File "/app/amp/core/finance.py", line 250, in resample_bars
    resampled = _resample_with_aggregate_function(
  File "/app/amp/core/finance.py", line 226, in _resample_with_aggregate_function
    hdbg.dassert_is_subset(cols, df.columns)
  File "/app/amp/helpers/dbg.py", line 370, in dassert_is_subset
    _dfatal(txt, msg, *args)
  File "/app/amp/helpers/dbg.py", line 115, in _dfatal
    dfatal(dfatal_txt)
  File "/app/amp/helpers/dbg.py", line 61, in dfatal
    raise assertion_type(ret)
AssertionError:
################################################################################
* Failed assertion *
val1={'close'}
issubset
val2={('asset_id', 101),
 ('close', 101),
 ('start_datetime', 101),
 ('timestamp_db', 101),
 ('volume', 101)}
val1 - val2={'close'}
################################################################################
```

We are running a single asset but multi-index, so I think it might be related to handling of some corner case.

I'll merge the PR disabling this test.

**Comment by gpsaggese** [comment]
After the previous one is fixed I think we are back to the problem that the `OrderProcessor` should wait for longer than 5 mins since the first 5 minutes we likely have no forecast.

**Comment by gitpaulsmith** [comment]
- The first problem is that we are calling the wrong DAG (`ReturnsBuilder` instead of `MvnReturnsBuilder`)
- Once we swap in the correct DAG, we need to remove the source node so that the adapter works properly
- Next, we are using "2000-01-01" as the start date, which is a Saturday, and so we have all-NaN market data
- After that, we aren't generating our first usable prediction until 9:40am, which is when we are hitting the timeout
- Still getting a timeout, which I think is due to `run_leq_node:  83%|████████▎ | 5/6 [00:00<00:00,  7.45it/s]/app/amp/dataflow/system/dataflow_sink_nodes.py:62: RuntimeWarning: coroutine 'process_forecasts' was never awaited`

**Comment by gitpaulsmith** [comment]
WIP in branch `AmpTask1946_Run_the_RT_pipeline_with_MockedBrokerPortfolio_08`

**Comment by gitpaulsmith** [comment]
My suspicion is that since we've added an awaitable node to the end of the DAG, the `predict()` method, at least for that final node, now needs to be awaitable (i.e. in the class `ProcessForecasts`). Unfortunately, because we use a lot of machinery around the DAG to execute, "everything" may need to become async to support our current flow. I also suspect that we aren't seeing this in `test_real_time_dag_adapter.py` because there we only test the case `event_loop = None`.
