### ISSUE TITLE
Update tests after pandas update

### ISSUE THREAD

**Issue by gpsaggese** [alphamatic/amp#2200]
```
1814 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2895320Z =================================== FAILURES ===================================
1815 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2896051Z ^[[31m^[[1m____________________ Test_compute_signed_run_lengths.test4 _____________________^[[0m
1816 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2896581Z Traceback (most recent call last):
1817 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2897027Z   File "/app/core/statistics/test/test_signed_runs.py", line 283, in test4
1818 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2897603Z     pd.testing.assert_series_equal(actual, expected)
1819 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2898379Z   File "/venv/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1019, in assert_series_equal
1820 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2899028Z     assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
1821 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2899807Z   File "/venv/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 506, in assert_attr_equal
1822 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2900414Z     raise_assert_detail(obj, msg, left_attr, right_attr)
1823 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2901166Z   File "/venv/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 682, in raise_assert_detail
1824 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2901644Z     raise AssertionError(msg)
1825 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2902159Z AssertionError: Attributes of Series are different
1826 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2902404Z
1827 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2902551Z Attribute "dtype" are different
1828 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2902986Z [left]:  int64
1829 Run_fast_tests  Run fast tests  2022-02-19T20:19:43.2903272Z [right]: float64
```

**Comment by gpsaggese** [comment]
More tests are affected by 

```
# TestRealTimePipelineWithOms1.test1
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 769, in _validate_tuple_indexer
    self._validate_key(k, i)
  File "/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1378, in _validate_key
    raise ValueError(f"Can only index by location with a [{self._valid_types}]")
ValueError: Can only index by location with a [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/dataflow/pipelines/real_time/test/test_dataflow_pipelines_real_time_pipeline.py", line 225, in test1
    result_bundles = hasynci.run(
  File "/app/helpers/hasyncio.py", line 140, in run
    ret = event_loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/dataflow/system/real_time_dag_runner.py", line 57, in predict
    result_bundles = [
  File "/app/dataflow/system/real_time_dag_runner.py", line 57, in <listcomp>
    result_bundles = [
  File "/app/dataflow/system/real_time_dag_runner.py", line 72, in predict_at_datetime
    async for event, result_bundle in creatime.execute_with_real_time_loop(
  File "/app/core/real_time.py", line 394, in execute_with_real_time_loop
    result = await asyncio.gather(  # type: ignore[var-annotated]
  File "/app/dataflow/system/real_time_dag_runner.py", line 123, in _run_dag
    await node.process_forecasts()
  File "/app/dataflow/system/sink_nodes.py", line 61, in process_forecasts
    await oprofore.process_forecasts(
  File "/app/oms/process_forecasts.py", line 181, in process_forecasts
    await forecast_processor.submit_orders(orders)
  File "/app/oms/process_forecasts.py", line 322, in submit_orders
    _LOG.debug("portfolio=\n%s" % str(self._portfolio))
  File "/app/oms/portfolio.py", line 149, in __str__
    self.get_historical_pnl(),
  File "/app/oms/portfolio.py", line 377, in get_historical_pnl
    pnl = self._compute_pnl(mtm, flows)
  File "/app/oms/portfolio.py", line 534, in _compute_pnl
    pnl = holdings_marked_to_market.diff().add(flows)
  File "/venv/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 424, in f
    return frame_arith_method_with_reindex(self, other, op)
  File "/venv/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 364, in frame_arith_method_with_reindex
    new_left = left.iloc[:, lcols]
  File "/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1458, in _getitem_tuple
    tup = self._validate_tuple_indexer(tup)
  File "/venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 771, in _validate_tuple_indexer
    raise ValueError(
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types
```

**Comment by gpsaggese** [comment]
```
dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean (0.04 s) FAILED                                                                                                                                                                                                                     [100%]

============================================================================================================================================================ FAILURES =============================================================================================================================================================
________________________________________________________________________________________________________________________________________ TestCrossSectionalDfToDfTransformer1.test_demean _________________________________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "/app/dataflow/core/nodes/test/test_transformers.py", line 320, in test_demean
    expected = pd.read_csv(
  File "/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1231, in _make_engine
    return mapping[engine](f, **self.options)
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 92, in __init__
    ) = self._extract_multi_indexer_columns(
  File "/venv/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 315, in _extract_multi_indexer_columns
    raise ParserError("Header rows must have an equal number of columns.")
pandas.errors.ParserError: Header rows must have an equal number of columns.
======================================================================================================================================================= slowest 3 durations =======================================================================================================================================================
0.13s call     dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean
0.00s setup    dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean
0.00s teardown dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean
```

**Comment by gpsaggese** [comment]
In amp-1.1.0 a recent update of git is giving issues

```
root@b6ec211211d4:/app/amp# git rev-parse --show-toplevel
fatal: unsafe repository ('/app/amp' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /app/amp
```

while amp-1.0.3
```
root@436902bb3cbe:/app/amp# git rev-parse --show-toplevel
/app/amp
```

Other people are reporting the same problem (see https://github.com/actions/checkout/issues/760)

**Comment by gpsaggese** [comment]
The above was solved by adding a `git config` in the entrypoint

**Comment by gpsaggese** [comment]
Next 
```
i docker_cmd --stage local --version 1.1.0 --cmd "pytest im_v2/ccxt/data/extract/test/test_download_realtime_for_one_exchange.py::TestDownloadRealtimeForOneExchange1::test_parser"

Traceback (most recent call last):
  File "/app/amp/helpers/hsql_test.py", line 89, in setUpClass
    hsql.wait_db_connection(*connection_info)
  File "/app/amp/helpers/hsql_implementation.py", line 170, in wait_db_connection
    raise psycop.OperationalError(
psycopg2.OperationalError: Cannot connect to db host=localhost dbname=im_postgres_db_local port=5432 due to timeout=30 seconds
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Network is unreachable
        Is the server running on that host and accepting TCP/IP connections?
```

**Comment by gpsaggese** [comment]
The problem is that we rely on the name of the host (e.g., dev4) to know if dind is available. This works outside but not inside docker since the name of the host in Docker is not the name of the host of the host.

One approach is to detect dind support directly with
https://stackoverflow.com/questions/51834978/ip-command-is-missing-from-ubuntu-docker-image

**Comment by gpsaggese** [comment]
After a few more fixes the failing tests are:
```
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_get_end_ts_for_symbol1 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_get_start_ts_for_symbol1 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data1 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data2 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data3 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data4 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data5 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data6 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/talos/data/client/test/test_talos_clients.py::TestTalosHistoricalPqByTileClient2::test_read_data7 - configparser.NoSectionError: No section: 'ck'
FAILED im_v2/ccxt/data/extract/test/test_download_historical_data.py::TestDownloadHistoricalData1::test_parser - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_ohlcv_data2 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_ohlcv_data_invalid_input1 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_ohlcv_data_invalid_input2 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_ohlcv_data_invalid_input3 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_ohlcv_data_invalid_input4 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_order_book - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_download_order_book_invalid_input1 - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_get_exchange_currency_pairs - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED im_v2/ccxt/data/extract/test/test_exchange_class.py::TestCcxtExchange1::test_initialize_class - botocore.exceptions.ProfileNotFound: The config profile (ck) could not be found
FAILED dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean - pandas.errors.ParserError: Header rows must have an equal number of columns.
FAILED helpers/test/test_lib_tasks.py::TestLibTasksGetDockerCmd1::test_docker_bash4 - RuntimeError:
FAILED helpers/test/test_lib_tasks.py::TestLibTasksGetDockerCmd1::test_docker_bash5 - RuntimeError:
FAILED helpers/test/test_traceback.py::Test_Traceback1::test_parse4 - RuntimeError:
FAILED helpers/test/test_traceback.py::Test_Traceback1::test_parse5 - RuntimeError:
FAILED helpers/test/test_git.py::Test_git_path1::test_get_path_from_git_root1 - ValueError: Can't normalize file_name='/app/helpers/test/test_git.py' for git_root='/app/amp'
FAILED core/statistics/test/test_signed_runs.py::Test_compute_signed_run_lengths::test4 - AssertionError: Attributes of Series are different
```

**Comment by gpsaggese** [comment]
The fast tests failing are now

```
FAILED amp/dataflow/core/nodes/test/test_transformers.py::TestCrossSectionalDfToDfTransformer1::test_demean - pandas.errors.ParserError: Header rows must have an equal number of columns.
FAILED amp/helpers/test/test_lib_tasks.py::Test_generate_compose_file1::test1 - RuntimeError:
FAILED amp/helpers/test/test_lib_tasks.py::Test_generate_compose_file1::test2 - RuntimeError:
FAILED dataflow_lime/pipelines/E8/test/test_E8d_pipeline.py::Test_E8d_DagBuilder4::test_fit - RuntimeError:
FAILED amp/core/statistics/test/test_signed_runs.py::Test_compute_signed_run_lengths::test4 - AssertionError: Attributes of Series are different
```
